export const FORM_UPDATE_VALUE = "FORM_UPDATE_VALUE";
export const FORM_RESET = "FORM_RESET";
export const WEB3_NEWSTATE = "WEB3_NEWSTATE";
export const GIVETHDIRECTORY_NEWSTATE = "GIVETHDIRECTORY_NEWSTATE";
export const ADD_MILESTONE = "ADD_MILESTONE";
