export const FORM_UPDATE_VALUE = "FORM_UPDATE_VALUE";
export const FORM_RESET = "FORM_RESET";
export const WEB3_NEWSTATE = "WEB3_NEWSTATE";
export const GIVETHDIRECTORY_NEWSTATE = "GIVETHDIRECTORY_NEWSTATE";
export const deploymentActions = {
    UPDATE_CAMPAIGN_VALUES: "UPDATE_CAMPAIGN_VALUES",
    RUN_UNSTARTED: "RUN_UNSTARTED",
    RUN_IN_PROGRESS: "RUN_IN_PROGRESS",
    RUN_COMPLETE: "RUN_COMPLETE",
    RUN_ERROR: "RUN_ERROR",
    REMOVE_ERROR: "REMOVE_ERROR",
    UPDATE_DEPLOYMENT_STEP: "UPDATE_DEPLOYMENT_STEP",
    DEPLOYMENT_COMPLETE: "DEPLOYMENT_COMPLETE",
    SET_DEPLOYMENT_RESULTS: "SET_DEPLOYMENT_RESULTS",
    RESET: "RESET",
    CANCEL: "CANCEL",
};
export const userActions = {
    SET_ACCOUNT: "SET_ACCOUNT",
};
export const transactionActions = {
    NEW_TRANSATION: "NEW_TRANSACTION",
    TRANSACTION_MINED: "TRANSACTION_MINED",
    DISMISS_TRANSACTION: "DISMISS_TRANSACTION",
};
